const formOption = {
  alignItemLabels: true,
  alignItemLabelsInAllGroups: true,
  formData: {
    ID: 1,
    Name: 'John Heart',
    Position: 'CEO',
    BirthDate: '1964/03/16',
    HireDate: '1995/01/15',
    Notes:
      'John has been in the Audio/Video industry since 1990. He has led DevAV as its CEO since 2003.\r\nWhen not working hard as the CEO, John loves to golf and bowl. He once bowled a perfect game of 300.',
    Address: '351 S Hill St.',
    City: 'Los Angeles',
    State: 'CA',
    ZipCode: '90013',
    Home: '555-684-1334',
    Mobile: '555-684-1335',
    Email: 'jheart@dx-email.com',
    Skype: 'jheart_DX_skype',
  },
  labelLocation: 'left',
  labelMode: 'outside',
  minColWidth: '200',
  readOnly: false,
  requiredMark: '*',
  requiredMessage: '该项必填',
  showColonAfterLabel: true,
  showRequiredMark: true,
  showValidationSummary: 'false',
  colCount: '4',
  schemas: [
    {
      colSpan: 1,
      dataField: 'ID',
      editorOptions: { mode: 'text', readonly: false, name: 'dxTextBox' },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'Name',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'Position',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'BirthDate',
      editorOptions: {
        showClearButton: true,
        useMaskBehavior: true,
        displayFormat: 'yyyy-MM-dd hh:mm:ss',
        type: 'datetime',
        showAnalogClock: false,
      },
      editorType: 'dxDateBox',
    },
    {
      colSpan: 1,
      dataField: 'HireDate',
      editorOptions: {
        showClearButton: true,
        useMaskBehavior: true,
        displayFormat: 'yyyy-MM-dd',
        type: 'date',
        showAnalogClock: false,
      },
      editorType: 'dxDateBox',
    },
    {
      colSpan: 1,
      dataField: 'Address',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'City',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'State',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'ZipCode',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'Home',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'Mobile',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'Email',
      editorOptions: { mode: 'email', readonly: false },
      editorType: 'dxTextBox',
    },
    {
      colSpan: 1,
      dataField: 'Skype',
      editorOptions: { mode: 'text', readonly: false },
      editorType: 'dxTextBox',
    },
  ],
};

export default formOption;
